import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const app = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
const styles = readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8')
const indexHtml = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
const favicon = readFileSync(new URL('../public/favicon.svg', import.meta.url), 'utf8')

test('navigation switches single-screen panels without anchor scrolling', () => {
  assert.match(app, /const activeView = ref\('generator'\)/)
  assert.match(app, /\{ id: 'generator', label: '首页' \}/)
  assert.match(app, /@click="switchView\('generator'\)"/)
  assert.match(app, /aria-current="activeView === item\.id \? 'page'/)
  assert.match(app, /v-show="activeView === 'generator'"/)
  assert.match(app, /v-show="activeView === 'history'"/)
  assert.doesNotMatch(app, /\{ id: 'home'/)
  assert.doesNotMatch(app, /\{ id: 'method'/)
  assert.doesNotMatch(app, /v-show="activeView === '(?:home|method)'"/)
  assert.doesNotMatch(app, /scrollIntoView/)
  assert.doesNotMatch(app, /href="#/)
})

test('browser and brand titles use the requested name', () => {
  assert.match(indexHtml, /<title>彩票预测-双色球<\/title>/)
  assert.match(app, /<strong>彩票预测-双色球<\/strong>/)
})

test('brand and browser icons use the same softer palette', () => {
  assert.match(indexHtml, /href="\/favicon\.svg\?v=6"/)
  assert.match(styles, /--brand-red:\s*#ed7b7c/)
  assert.match(styles, /--brand-blue:\s*#6f91d2/)
  assert.match(styles, /background:\s*var\(--brand-red\)/)
  assert.match(styles, /border:\s*6px solid var\(--brand-blue\)/)
  assert.match(favicon, /viewBox="0 0 44 44"/)
  assert.match(favicon, /<rect width="44" height="44" rx="9" fill="#e4e1da"\/>/)
  assert.match(favicon, /<g transform="translate\(7\.125 7\.125\) scale\(0\.875\)">/)
  assert.match(favicon, /<circle cx="12" cy="12" r="12" fill="#ed7b7c"\/>/)
  assert.match(favicon, /<circle cx="22" cy="22" r="12" fill="#6f91d2"\/>/)
  assert.match(favicon, /<circle cx="22" cy="22" r="6" fill="#f4f2ed"\/>/)
})

test('all records render without pagination controls or pagination state', () => {
  assert.match(app, /v-for="ticket in result\.tickets"/)
  assert.match(app, /v-for="group in result\.compoundGroups"/)
  assert.match(app, /v-for="draw in historyRows"/)
  assert.doesNotMatch(app, /screen-pagination|trend-pagination/)
  assert.doesNotMatch(app, /PageCount|PageSize|change\w*Page|paginate\(/)
  assert.match(app, /generatorPane/)
  assert.match(app, /statisticsPane/)
})

test('compound generation defaults to configurable seven plus two and exposes result copying', () => {
  assert.match(app, /ticketCount:\s*2/)
  assert.equal((app.match(/form\.ticketCount = 2/g) || []).length, 2)
  assert.match(app, /compoundRedCount:\s*7/)
  assert.match(app, /compoundBlueCount:\s*2/)
  assert.match(app, /v-model\.number="form\.compoundRedCount"/)
  assert.match(app, /v-model\.number="form\.compoundBlueCount"/)
  assert.match(app, /compoundExpandedPerGroup/)
  assert.match(app, /C\(\{\{ form\.compoundRedCount \}\},6\)/)
  assert.doesNotMatch(app, /<option value="COMPOUND_7_2">/)
  assert.match(app, /<option value="COMPOUND">复式<\/option>/)
  assert.match(app, /<option value="STANDARD">单式<\/option>/)
  assert.doesNotMatch(app, /<option[^>]*>(?:复式（自选几\+几）|单式 \/ 旋转矩阵)<\/option>/)
  assert.doesNotMatch(app, /任选 [61] 个/)
  assert.match(app, /<\/select>\s*<\/label>\s*<div v-if="compoundMode" class="compound-spec wide-field">[\s\S]*?<span>\{\{ compoundMode \? '复式组数'/)
  assert.match(app, /class="field-grid" :class="\{ 'compound-field-grid': compoundMode \}"/)
  assert.match(app, /class="compound-spec-summary"/)
  assert.match(styles, /\.compound-field-grid\s*\{[^}]*grid-template-rows:\s*minmax\(54px, 1fr\) minmax\(171px, 2fr\) repeat\(3, minmax\(54px, 1fr\)\)/s)
  assert.match(styles, /\.compound-spec-summary\s*\{[^}]*position:\s*relative[^}]*height:\s*81px/s)
  assert.match(styles, /\.compound-spec-summary > strong\s*\{[^}]*top:\s*40%/s)
  assert.match(styles, /\.compound-spec-summary > small\s*\{[^}]*top:\s*80%/s)
  assert.match(app, /<label v-if="!compoundMode" class="wide-field">\s*<span>复现种子/)
  assert.match(app, /if \(isCompoundMode\(mode\)\) \{\s*form\.seed = null/)
  assert.match(app, /class="copy-result-button"/)
  assert.match(app, /@click="copyGeneratedNumbers"/)
  assert.match(styles, /\.compound-grid\s*\{[^}]*padding-right:\s*0[^}]*scrollbar-gutter:\s*auto/s)
})

test('select arrows keep space from the right border', () => {
  assert.match(styles, /select\s*\{[^}]*appearance:\s*none[^}]*background-image:\s*url\([^}]*background-position:\s*right 16px center/s)
  assert.doesNotMatch(styles, /input,\s*select\s*\{[^}]*appearance:\s*none/s)
  assert.match(styles, /\.field-grid select\s*\{[^}]*padding:\s*0 38px 0 12px/s)
  assert.match(styles, /\.trend-limit select\s*\{[^}]*background-position:\s*right 10px center/s)
})

test('compound result labels and formulas use the selected ball counts', () => {
  assert.match(app, /group\.redBalls\.length \}\}\+\{\{ group\.blueBalls\.length/)
  assert.match(app, /红球 · \{\{ group\.redBalls\.length \}\} 选 6/)
  assert.match(app, /蓝球 · \{\{ group\.blueBalls\.length \}\} 选 1/)
  assert.match(app, /group\.expandedTicketCount/)
  assert.doesNotMatch(app, /第 \{\{ expandedGroup\.sequence \}\} 组 · 14 注展开/)
})

test('compound results stay in two columns and scroll downward after four cards', () => {
  assert.doesNotMatch(styles, /\.results-section\s*\{[^}]*padding-block/s)
  assert.match(styles, /\.screen\s*\{[^}]*padding:\s*clamp\(14px, 2\.2vh, 28px\) 0/s)
  assert.doesNotMatch(styles, /\.results-section \.section-heading\s*\{[^}]*margin-bottom/s)
  assert.match(styles, /\.section-heading\s*\{[^}]*margin-bottom:\s*clamp\(10px, 1\.7vh, 18px\)/s)
  assert.match(styles, /\.compound-grid\s*\{[^}]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)[^}]*grid-auto-flow:\s*row[^}]*overflow-x:\s*hidden[^}]*overflow-y:\s*auto/s)
  assert.match(styles, /@media\s*\(max-width:\s*1080px\)\s*\{[\s\S]*?\.compound-grid\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)/s)
  assert.match(styles, /\.compound-card\s*\{[^}]*padding:\s*clamp\(12px,\s*1\.6vh,\s*16px\)/s)
  assert.match(styles, /\.compound-ball-groups\s*\{[^}]*padding:\s*clamp\(10px,\s*1\.7vh,\s*16px\) 0/s)
})

test('root stays fixed while dense content scrolls inside the active screen', () => {
  assert.match(styles, /height:\s*100dvh/)
  assert.match(styles, /grid-template-rows:\s*auto minmax\(0, 1fr\)/)
  assert.match(styles, /\.workspace\s*\{[^}]*height:\s*100%[^}]*overflow:\s*hidden/s)
  assert.match(styles, /html,\s*body,\s*#app\s*\{[^}]*overflow:\s*hidden/s)
  assert.match(styles, /\.screen\s*\{[^}]*overflow:\s*auto/s)
  assert.match(styles, /\.trend-view\s*\{[^}]*overflow:\s*auto/s)
  assert.match(styles, /\.history-table-wrap\s*\{[^}]*overflow:\s*auto/s)
  assert.doesNotMatch(styles, /pagination/)
})

test('responsive workbench uses available panel space', () => {
  assert.match(app, /:class="\{ 'wide-field': !matrixEnabled \}"/)
  assert.match(styles, /width:\s*min\(1600px, calc\(100% - 48px\)\)/)
  assert.match(styles, /grid-template-rows:\s*repeat\(6, minmax\(54px, 1fr\)\)/)
  assert.match(styles, /grid-template-rows:\s*repeat\(5, minmax\(56px, 1fr\)\)/)
  assert.match(styles, /\.generator-grid > \.panel\s*\{[^}]*display:\s*flex[^}]*flex-direction:\s*column/s)
})

test('statistics panels distribute rows across available height', () => {
  assert.match(styles, /\.frequency-panel,\s*\.compact-panel\s*\{[^}]*display:\s*flex[^}]*flex-direction:\s*column/s)
  assert.match(styles, /\.side-statistics\s*\{[^}]*grid-template-rows:\s*minmax\(0, 0\.8fr\) minmax\(0, 1\.2fr\)/s)
  assert.match(styles, /\.red-frequency\s*\{[^}]*grid-auto-rows:\s*minmax\(34px, 1fr\)/s)
  assert.match(styles, /\.blue-frequency\s*\{[^}]*grid-auto-rows:\s*minmax\(32px, 1fr\)/s)
  assert.match(styles, /\.sample-groups\s*\{[^}]*grid-template-rows:\s*repeat\(2, minmax\(0, 1fr\)\)/s)
})

test('trend and history data use readable type and ball sizes', () => {
  assert.match(app, /点击红球或蓝球切换走势，实心球表示当期开奖，灰色数字表示连续遗漏期数/)
  assert.match(app, /const trendType = ref\('red'\)/)
  assert.match(app, /class="trend-tabs"/)
  assert.doesNotMatch(app, /trend-ranges|trendRangeIndex|activeTrendRange/)
  assert.match(app, /v-for="number in trendNumbers"/)
  assert.match(app, /v-for="row in trendRows"/)
  assert.match(styles, /\.trend-table th,\s*\.trend-table td\s*\{[^}]*height:\s*42px/s)
  assert.match(styles, /\.trend-table thead th\s*\{[^}]*height:\s*33px[^}]*font:\s*600 12px\/1\.2/s)
  assert.match(styles, /\.trend-cell span\s*\{[^}]*width:\s*min\(32px[^}]*font:\s*600 12px\/1/s)
  assert.match(styles, /\.trend-cell em\s*\{[^}]*font:\s*normal 11px\/1/s)
  assert.match(styles, /\.history-table th\s*\{[^}]*height:\s*36px[^}]*font-size:\s*12px/s)
  assert.match(styles, /\.history-table td\s*\{[^}]*height:\s*43px[^}]*font-size:\s*14px/s)
  assert.match(styles, /\.status-grid strong\.success\s*\{[^}]*font-weight:\s*700/s)
  assert.match(styles, /\.history-table i\s*\{[^}]*width:\s*30px[^}]*height:\s*30px[^}]*background:\s*var\(--red\)[^}]*color:\s*#fff[^}]*font:\s*600 11px\/1 var\(--mono\)[^}]*box-shadow:\s*0 2px 5px rgba\(185, 31, 45, 0\.18\)/s)
  assert.match(styles, /\.history-table \.history-blue\s*\{[^}]*background:\s*var\(--blue\)[^}]*color:\s*#fff[^}]*box-shadow:\s*0 2px 5px rgba\(36, 92, 199, 0\.2\)/s)
  assert.match(styles, /\.trend-table\.trend-red\s*\{[^}]*min-width:\s*1320px/s)
  assert.match(styles, /\.trend-table\.trend-blue\s*\{[^}]*min-width:\s*800px/s)
  assert.match(styles, /\.history-table\s*\{[^}]*min-width:\s*680px/s)
})

test('history draw columns are balanced and red balls use explicit spacing', () => {
  assert.match(app, /class="history-red-balls"/)
  assert.match(styles, /\.history-table th:first-child,\s*\.history-table td:first-child\s*\{[^}]*width:\s*18%/s)
  assert.match(styles, /\.history-table th:nth-child\(2\),\s*\.history-table td:nth-child\(2\)\s*\{[^}]*width:\s*20%/s)
  assert.match(styles, /\.history-table th:nth-child\(3\),\s*\.history-table td:nth-child\(3\)\s*\{[^}]*width:\s*44%/s)
  assert.match(styles, /\.history-table th:last-child,\s*\.history-table td:last-child\s*\{[^}]*width:\s*18%/s)
  assert.match(styles, /\.history-table th,\s*\.history-table td\s*\{[^}]*text-align:\s*center/s)
  assert.match(styles, /\.history-red-balls\s*\{[^}]*display:\s*inline-flex[^}]*gap:\s*8px/s)
})
